### ISSUE TITLE
Punica/s-lora integration

### ISSUE THREAD

**Issue by nivibilla** [FasterDecoding/BitDelta#4]
Hi,

It mentioned in the blog that you were able to improve performance by 2x with bitdelta with punica.

Are you planning to release that implementation too?

https://www.together.ai/blog/bitdelta

**Comment by chromecast56** [comment]
Hey Srinivas - In terms of decoding latency, we don't make a comparison to punica but rather to the case where you inference on B distinct fine-tune models at the same time. For our implementation, we use our `batched_bmm` kernel [here](https://github.com/FasterDecoding/BitDelta/blob/main/bitdelta/binary_gemm_kernel.py#L297).
